# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

"""TileLang DSL v1 package."""

from .kernel import (
    BoundKernelParameter,
    InlineProcDescriptor,
    KernelRegistry,
    MaterializedMLIRModule,
    TileLangFrontendError,
    VKernelDescriptor,
    inline_proc,
    select_kernel,
    vkernel,
)
from .types import (
    AnyFloat,
    AnyInt,
    AnyMask,
    AnyType,
    AlignType,
    BLayout,
    DeinterleaveDist,
    EVENT,
    PIPE,
    Event,
    InterleaveDist,
    MaskType,
    MemorySpace,
    MaskPattern,
    PAT,
    PadValue,
    PadMode,
    PositionMode,
    OrderMode,
    PointerType,
    Pipe,
    ScalarType,
    StrideMode,
    TensorView,
    PartitionTensorView,
    Tile,
    TileConfig,
    TileSpecialization,
    TypeVar,
    TypeVariable,
    VRegType,
    WildcardType,
    align,
    bf16,
    constexpr,
    bytewidth,
    elements_per_vreg,
    f16,
    f32,
    get_lanes,
    i1,
    i8,
    i16,
    i32,
    i64,
    mask_b8,
    mask_b16,
    mask_b32,
    ptr,
    SLayout,
    vreg,
)

__all__ = [
    "BoundKernelParameter",
    "InlineProcDescriptor",
    "KernelRegistry",
    "MaterializedMLIRModule",
    "TileLangFrontendError",
    "VKernelDescriptor",
    "inline_proc",
    "select_kernel",
    "vkernel",
    "ScalarType",
    "WildcardType",
    "TypeVariable",
    "TypeVar",
    "TensorView",
    "PartitionTensorView",
    "Tile",
    "PointerType",
    "VRegType",
    "MaskType",
    "AlignType",
    "ptr",
    "vreg",
    "MemorySpace",
    "BLayout",
    "SLayout",
    "PadValue",
    "Pipe",
    "Event",
    "PIPE",
    "EVENT",
    "MaskPattern",
    "PAT",
    "PadMode",
    "PositionMode",
    "OrderMode",
    "DeinterleaveDist",
    "InterleaveDist",
    "StrideMode",
    "TileConfig",
    "TileSpecialization",
    "i1",
    "i8",
    "i16",
    "i32",
    "i64",
    "f16",
    "bf16",
    "f32",
    "AnyFloat",
    "AnyInt",
    "AnyType",
    "AnyMask",
    "align",
    "mask_b8",
    "mask_b16",
    "mask_b32",
    "constexpr",
    "bytewidth",
    "get_lanes",
    "elements_per_vreg",
]
